# Generated by Django 4.2 on 2025-11-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='codes/'),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('javascript', 'JavaScript'), ('c', 'C'), ('html', 'HTML'), ('css', 'CSS'), ('other', 'Other')], max_length=50),
        ),
    ]
