# Generated by Django 5.2.8 on 2025-11-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0003_codesnippet_deleted_at_codesnippet_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='snippets/'),
        ),
    ]
