# Generated by Django 5.2.8 on 2025-11-20 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0004_alter_codesnippet_code_alter_codesnippet_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
