# Generated by Django 5.2.8 on 2025-11-23 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0007_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='reports_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codesnippets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
