# Generated by Django 5.2.8 on 2025-11-23 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0008_codesnippet_downloads_codesnippet_likes_and_more'),
    ]

    operations = [
    ]
